// ===================================================================================
//  Written by (NL)NOOTLORD 
//  Fancy new crosshairs, all credit goes to Kenney (www.kenney.nl)
// ===================================================================================
class BN4Crosshairs extends CrosshairPack
	notplaceable;

DefaultProperties
{
	Crosshair(0)=(FriendlyName="Dot",CrosshairTexture=Texture'BN4Crosshairs.Hud.crosshair_dot')
	Crosshair(1)=(FriendlyName="Dots",CrosshairTexture=Texture'BN4Crosshairs.Hud.crosshair_dots')
	Crosshair(2)=(FriendlyName="Cross 1",CrosshairTexture=Texture'BN4Crosshairs.Hud.crosshair_cross1')
	Crosshair(3)=(FriendlyName="Cross 2",CrosshairTexture=Texture'BN4Crosshairs.Hud.crosshair_cross2')
	Crosshair(4)=(FriendlyName="Cross 3",CrosshairTexture=Texture'BN4Crosshairs.Hud.crosshair_cross3')
	Crosshair(5)=(FriendlyName="Cross 4",CrosshairTexture=Texture'BN4Crosshairs.Hud.crosshair_cross4')
	Crosshair(6)=(FriendlyName="Cross 5",CrosshairTexture=Texture'BN4Crosshairs.Hud.crosshair_cross5')
	Crosshair(7)=(FriendlyName="Cross 6",CrosshairTexture=Texture'BN4Crosshairs.Hud.crosshair_cross6')
	Crosshair(8)=(FriendlyName="Cross 7",CrosshairTexture=Texture'BN4Crosshairs.Hud.crosshair_cross7')
	Crosshair(9)=(FriendlyName="Cross 8",CrosshairTexture=Texture'BN4Crosshairs.Hud.crosshair_cross8')
	Crosshair(10)=(FriendlyName="Cross 9",CrosshairTexture=Texture'BN4Crosshairs.Hud.crosshair_cross9')
	Crosshair(11)=(FriendlyName="Cross 10",CrosshairTexture=Texture'BN4Crosshairs.Hud.crosshair_cross10')
	Crosshair(12)=(FriendlyName="Cross 11",CrosshairTexture=Texture'BN4Crosshairs.Hud.crosshair_cross11')
	Crosshair(13)=(FriendlyName="Circle 1",CrosshairTexture=Texture'BN4Crosshairs.Hud.Crosshair_Circle1')	
	Crosshair(14)=(FriendlyName="Circle 2",CrosshairTexture=Texture'BN4Crosshairs.Hud.Crosshair_Circle2')	
	Crosshair(15)=(FriendlyName="Circle 3",CrosshairTexture=Texture'BN4Crosshairs.Hud.Crosshair_Circle3')	
	Crosshair(16)=(FriendlyName="Circle 4",CrosshairTexture=Texture'BN4Crosshairs.Hud.Crosshair_Circle4')	
	Crosshair(17)=(FriendlyName="Circle 5",CrosshairTexture=Texture'BN4Crosshairs.Hud.Crosshair_Circle5')	
	Crosshair(18)=(FriendlyName="Circle 6",CrosshairTexture=Texture'BN4Crosshairs.Hud.Crosshair_Circle6')	
	Crosshair(19)=(FriendlyName="Circle 7",CrosshairTexture=Texture'BN4Crosshairs.Hud.Crosshair_Circle7')	
	Crosshair(20)=(FriendlyName="Square 1",CrosshairTexture=Texture'BN4Crosshairs.Hud.Crosshair_Square1')	
	Crosshair(21)=(FriendlyName="Square 2",CrosshairTexture=Texture'BN4Crosshairs.Hud.Crosshair_Square2')		
	Crosshair(22)=(FriendlyName="Triangle 1",CrosshairTexture=Texture'BN4Crosshairs.Hud.Crosshair_Triangle1')
	Crosshair(23)=(FriendlyName="Triangle 2",CrosshairTexture=Texture'BN4Crosshairs.Hud.Crosshair_Triangle2')
	Crosshair(24)=(FriendlyName="Triangle 3",CrosshairTexture=Texture'BN4Crosshairs.Hud.Crosshair_Triangle3')
	Crosshair(25)=(FriendlyName="Triangle 4",CrosshairTexture=Texture'BN4Crosshairs.Hud.Crosshair_Triangle4')
	Crosshair(26)=(FriendlyName="Triangle 5",CrosshairTexture=Texture'BN4Crosshairs.Hud.Crosshair_Triangle5')
	Crosshair(27)=(FriendlyName="Triangle 6",CrosshairTexture=Texture'BN4Crosshairs.Hud.Crosshair_Triangle6')
	Crosshair(28)=(FriendlyName="Triangle 7",CrosshairTexture=Texture'BN4Crosshairs.Hud.Crosshair_Triangle7')
	Crosshair(29)=(FriendlyName="Triangle 8",CrosshairTexture=Texture'BN4Crosshairs.Hud.Crosshair_Triangle8')
	Crosshair(30)=(FriendlyName="Triangle 9",CrosshairTexture=Texture'BN4Crosshairs.Hud.Crosshair_Triangle9')
	Crosshair(31)=(FriendlyName="Triangle 10",CrosshairTexture=Texture'BN4Crosshairs.Hud.Crosshair_Triangle10')
	Crosshair(32)=(FriendlyName="Triangle 11",CrosshairTexture=Texture'BN4Crosshairs.Hud.Crosshair_Triangle11')
	Crosshair(33)=(FriendlyName="Triangle 12",CrosshairTexture=Texture'BN4Crosshairs.Hud.Crosshair_Triangle12')
	Crosshair(34)=(FriendlyName="Triangle 13",CrosshairTexture=Texture'BN4Crosshairs.Hud.Crosshair_Triangle13')
	Crosshair(35)=(FriendlyName="Triangle 14",CrosshairTexture=Texture'BN4Crosshairs.Hud.Crosshair_Triangle14')
	Crosshair(36)=(FriendlyName="Miscellaneous 1",CrosshairTexture=Texture'BN4Crosshairs.Hud.Crosshair_Misc1')
	Crosshair(37)=(FriendlyName="Miscellaneous 2",CrosshairTexture=Texture'BN4Crosshairs.Hud.Crosshair_Misc2')
	Crosshair(38)=(FriendlyName="Miscellaneous 3",CrosshairTexture=Texture'BN4Crosshairs.Hud.Crosshair_Misc3')
	Crosshair(39)=(FriendlyName="Miscellaneous 4",CrosshairTexture=Texture'BN4Crosshairs.Hud.Crosshair_Misc4')
	Crosshair(40)=(FriendlyName="Miscellaneous 5",CrosshairTexture=Texture'BN4Crosshairs.Hud.Crosshair_Misc5')
	Crosshair(41)=(FriendlyName="Miscellaneous 6",CrosshairTexture=Texture'BN4Crosshairs.Hud.Crosshair_Misc6')
	Crosshair(42)=(FriendlyName="Miscellaneous 7",CrosshairTexture=Texture'BN4Crosshairs.Hud.Crosshair_Misc7')
	Crosshair(43)=(FriendlyName="Miscellaneous 8",CrosshairTexture=Texture'BN4Crosshairs.Hud.Crosshair_Misc8')
}

